### ISSUE TITLE
TerrainQuad duplicate code

### ISSUE THREAD

**Issue by JordenvBreemen** [sandervdo/jmonkeyengine#2]
In terrainquad heb je 3 functies:

getHeightmapHeight
getMeshNormal
findMatchingChild

Die alle 3 vrijwel dezelfde body hebben maar verschillende return types en de laatste dingen in die loop zijn anders. Ik kon niet echt iets moois verzinnen om dit te combineren in 1 functie. Weet jij wat?

**Comment by sandervdo** [comment]
Die functies zitten ook in TerrainPatch geloof ik. Maybe een superclass die al die return types omvat? En de laatste step in een switch oid gooien en dan een selector meegeven?

``` java
callToHelperFunction(data, selector);

public SuperClass callToHelperFunction(Object data, Object selector) {
    ...

    switch (selector) {
        case ... : ...; break;
    }
}
```

**Comment by JordenvBreemen** [comment]
Zit volgens mij meer overlap tussen die twee, dan sws handig om het miss in een losse class te doen?
